<?php
/**
 * Created by PhpStorm.
 * User: xm
 * Date: 16/2/28
 * Time: 01:13
 */

namespace Home\Controller;
use Think\Category;
class AreaController extends CommonController{

    protected $area_obj;
    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->area_obj=D('area');
    }

    //区域列表
    public function index(){
        $list =$this->area_obj->select();
        $list = Category::unlimitForLayer($list);
        $this->assign('list',$list);
        $this->display();
    }


    public function lists(){

    }
}